id: A517448C2
base_file: f2EF2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:35.982116
  last_modified_at: 2022-06-17 12:32:35.982119
