id: A517448C2
base_file: fCB80.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.072343
  last_modified_at: 2022-06-17 12:32:36.072346
