id: A517448C2
base_file: f79D8.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.046759
  last_modified_at: 2022-06-17 12:32:36.046761
