id: A517448C2
base_file: f8689.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.058575
  last_modified_at: 2022-06-17 12:32:36.058578
