id: A517448C2
base_file: f3EE5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.016531
  last_modified_at: 2022-06-17 12:32:36.016537
