id: A517448C2
base_file: f33AE.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:35.984944
  last_modified_at: 2022-06-17 12:32:35.984947
