id: A517448C2
base_file: f80A4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.051642
  last_modified_at: 2022-06-17 12:32:36.051644
