id: A517448C2
base_file: fFADB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:32:36.078096
  last_modified_at: 2022-06-17 12:32:36.078099
